### ISSUE TITLE
Issue when removing item in v-for

### ISSUE THREAD

**Issue by fhusquinet** [konvajs/vue-konva#10]
Hi!

First of all thank you for the great package!

I ran into a small issue and I'm not sure how I could correct it.

I have a layer displaying a number of circles using a v-for loop. Adding circles work as expected but removing a point do not seem to update the canvas.

I tried to reproduce the issue using JSFiddle:
https://jsfiddle.net/eywraw8t/10786/

In this case no point seem to be deleted until add a new point, where as in my project the points are deleted in real time except for the last one which stays on the layer even though the array is empty.

Any idea where this could come from? 

Thanks in advance!

**Comment by Ldoppea** [comment]
Seems to be a bug from vue-konva.

After a deletion, the corresponding circle object is correctly destroyed by Vue-Konva but `layer.batchDraw()` is not called and so image is not updated.

In [applyNodeProps.js](https://github.com/rafaesc/vue-konva/blob/68296255ce6432f7f24af9afe7b7f7e26e84c3c0/src/utils/applyNodeProps.js) the `hasUpdates` variable is set to true when `props` is different than `oldProps`. But in the case of a deletion both `props` and `oldProps` are empty (and equals), so `hasUpdates` is not set to true.

I tried to add the following code and it seems to fix the bug : 
```
  if (Object.keys(props).length === 0 && props.constructor === Object) {
    hasUpdates = true;
  }
```

But I'm not sure if this is a good solution because rest of the code is still obscure to me. @rafaesc what do you think about it?

**Comment by lavrton** [comment]
I guess the layer should be updated with `destroyed` method.
Something like this:

```
destroyed() {
    var layer = this._stage.getLayer();
    this._stage.destroy();
    if (layer) {
         layer.batchDraw();
    }
},
```

**Comment by fhusquinet** [comment]
I tried @Ldoppea's solution which works but I have no idea what this could cause somewhere else either...
I tried doing something similar inside of my Vue application without any luck. Destroying the entire layer works but then it is impossible to create a new point on it and it sounds a bit overkill to do so.

**Comment by Ldoppea** [comment]
If you want a temporary fix for your code, you can do the `batchDraw` in the `updated` hook : 
```
  updated: function() {
  	this.$refs.layer.getStage().batchDraw()
  }
```
This is not optimized but as I said : this should be temporary.

**Comment by lavrton** [comment]
The bug should be fixed.
