### ISSUE TITLE
Animation Performance

### ISSUE THREAD

**Issue by Scaalees** [konvajs/vue-konva#100]
I've been playing little hiding custom shapes with the mouse cursor. 

https://codesandbox.io/s/vue-konva-shape-hide-fx70o

As you can see the performance suffers after a period. Is there something I'm missing for better performance?

Sorry if this has already been mentioned before, not sure what the best method is for this.

**Comment by lavrton** [comment]
I see two ways to improve it:
1. https://konvajs.org/docs/performance/Optimize_Strokes.html (disable stroke on hit graph)
2. https://konvajs.org/docs/performance/Disable_Perfect_Draw.html (skip extra drawing, it is required, because shapes have stroke + opacity).

https://codesandbox.io/s/vue-konva-shape-hide-t57x6
