### ISSUE TITLE
<v-text> align: 'center' not work

### ISSUE THREAD

**Issue by bludnic** [konvajs/vue-konva#11]
``<v-text :config="{
              x: 350,
              y: 10,
              text: 'Sample text',
              fill: 'white',
              fontSize: 36,
              align: 'center'
            }"></v-text>
``

Property 'align' does not have any effect.

https://konvajs.github.io/docs/shapes/Text.html

**Comment by Ldoppea** [comment]
Hi,

This is the expected behavior. The `align` property does not align the text around `x` position but it uses the text `width` property. So your text will be aligned around `x + width/2`.

You should add a `width` to your `v-text`:

`<v-text :config="{ x: 0, y: 10, width: 700, text: 'Sample text', fill: 'white', fontSize: 36, align: 'center' }"></v-text>`

`(x + width/2) = (0 + 700/2) = 350` : so the text will be aligned around `x=350`

Here is a demo to see how it works : https://codesandbox.io/s/ywpy22y77j

**Comment by bludnic** [comment]
@Ldoppea thanks, it works
