### ISSUE TITLE
How to use in NuxtJS?

### ISSUE THREAD

**Issue by clydesantiago** [konvajs/vue-konva#18]
How to use it in nuxt js? It always shows an error `Unknown custom element: <konva> - did you register the component correctly?` I've created `plugins/konva.js` and added it on my `nuxt.config.js` file `  plugins: [
    { src: '~/plugins/konva', ssr: false }
  ]`. But i can't access `v-stage` component or any other component

**Comment by clydesantiago** [comment]
Here's my `konva.js` file 

```
import Vue from 'vue';
import VueKonva from 'vue-konva'

Vue.use(VueKonva)
```

**Comment by Ldoppea** [comment]
Naive idea : did you try to rename your konva plugin? This may interfere with the base [konva](https://github.com/konvajs/konva) framework as it uses the same name.

I think @speed676 may be able to help you has he succeeded to use NuxtJS with Konva here : https://github.com/konvajs/vue-konva/issues/9

**Comment by clydesantiago** [comment]
@Ldoppea It's working now. Thank you

**Comment by nyknstyn** [comment]
> @Ldoppea It's working now. Thank you

What exactly fixed your issue?

**Comment by sjoerdoudman** [comment]
> > @Ldoppea It's working now. Thank you
> 
> What exactly fixed your issue?

I guess the renaming. I just tested the above naming the /plugins file vuekonva.js. Gets the job done

**Comment by hugoaboud** [comment]
I've had a similar issue with `<v-stage>` instead of `<konva>`.

Renaming didn't work. After some other attempts I've added a `console.log('anything')` to the `konva.js` to identify whether it was being called or not.
Turns out it worked. Then I've removed the `console.log` and it kept working. I proceeded to restart the project and it kept working. Pretty weird, since I also tried restarting a few times before.

I'm running in 'dev' mode, with hot reload, not sure if it relates to the issue.

**Comment by Aravinda93** [comment]
@clydesantiago  I am also trying to integrate the `vue-konva` with `Nuxt` and running into the same issue. I tried the `plugins` creation but got a different error. Can you please have a look at this question and suggest me? https://stackoverflow.com/q/69839090/7584240

Any suggestion would be really appreciated. Thanks in advance.

**Comment by Ldoppea** [comment]
Sorry I did not use konva nor vue-konva for a long time, I don't remember mechanisms that were involved, so i'm affraid that I won't be of any help here 😞
