### ISSUE TITLE
Does it have a mouse wheel event?

### ISSUE THREAD

**Issue by muuma** [konvajs/vue-konva#19]
Hi, I want to achieve a scrolling mouse wheel image zoom in and out. So, does it have a mousewheel event?

**Comment by Ldoppea** [comment]
Hi, you can use the `@wheel` property : 
```
<v-stage ref="stage" :config="configStage" @wheel="zoom">
...
</v-stage>
```
Then the zoom event should be used like this : 
```
zoom (element, event) {
  const deltaX = event.evt.deltaX;
  const deltaY = event.evt.deltaY;
}
```

Also you can find the list of other avaibable events here : https://konvajs.github.io/docs/events/Binding_Events.html

**Comment by arifhussain353** [comment]
Hi @lavrton,
I am reopening this issue because:-
`@wheel` event loss on `<stage>`  because of dom manipulation.
I bind the `@wheel` event to `<stage>`

![Screenshot from 2020-01-29 13-15-24](https://user-images.githubusercontent.com/12670763/73339435-a3e03c80-429a-11ea-9b69-355b68820716.png)

Now I want to `dispatch` this event by a click but it's not working reason is no wheel event listener.

![Screenshot from 2020-01-29 13-25-32](https://user-images.githubusercontent.com/12670763/73339574-dc801600-429a-11ea-8d41-2473de34dbff.png)
My code below:-
```
<div class="test" @click="manualZoom()">trigger wheel event of stage</div>

//method 
  manualZoom() {
      const dashboardStage =this.$refs.dashboardStage // getting ref of <stage>
      console.debug(dashboardStage,"dashboardStage") 
      let centerX = dashboardStage.clientLeft + dashboardStage.clientWidth / 2
      let centerY = dashboardStage.clientTop + dashboardStage.clientHeight / 2
      const event = new WheelEvent('wheel', {clientX: centerX, clientY: centerY, deltaY: value, deltaMode: 0})
      dashboardStage.dispatchEvent(event)
     },
```
This work when i bind same way on `HTML` parent `div` element.
Am I doing anything wrong?
