### ISSUE TITLE
Vue + Stage --> Have to force reload my browser (ctrl + r / ctrl + f5)

### ISSUE THREAD

**Issue by deathblade89** [konvajs/vue-konva#30]
Hi there,

I am experiencing somthing quite weird.

I have a stage that has draggable : true on.
I am using a vue CLI server to host this in debug environment.

When i just reload the page by simply browsing to it or pressing normal f5, the stage is not draggable until i force reload (ctrl + f5 or ctrl + r)

Do you think this is a development environment issue, or is this an issue with the vue-konva?

Thanks in advance.

Your library is amazing btw!

**Comment by lavrton** [comment]
@deathblade89 can you make a small online demo?

**Comment by lavrton** [comment]
For instance from this sandbox: https://codesandbox.io/s/github/konvajs/site/tree/master/vue-demos/basic_demo?from-embed

**Comment by deathblade89** [comment]
@lavrton 

I have made a small demo, but using the CodeSandbox i cannot replicate the issue.
https://codesandbox.io/s/10jn559mll

The configuration of the stage is identical to mine.

**Comment by deathblade89** [comment]
I will try to determine the root cause, but i fear it will be with no success.

**Comment by lavrton** [comment]
Works ok for me 😐

**Comment by maxwarch** [comment]
Hello,
I have a similar problem.
I make a component that include the v-stage and different v-layer + v-image. I'm using vue-router. I serialize the data with toJSON() and restore on navigate, no problem.

The problem is when i want to save dataURL : when i'm on a page containing the component and i navigate to the next page, also containing the component, i can't save dataURL :
konva.js:1083 Konva warning: Unable to get data URL. Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
When i refresh this page, i can save data URL.

Can you see the problem ?
I try to redraw the stage, $forceUpdate Vue and destroy stage on the previous page but nothing work.
Thanks for your help.

**Comment by deathblade89** [comment]
@lavrton 

I am still receiving the same problem, thought i could rebind the events on mounted instead of in configuration.

If I load the page with the the stage on it then navigate to a different page and then return the stage it is not draggable at all.

* I am using Vue + vue-router.
* I have tried to set the dragbound function in the mounted event as opposed to in the data configuration.
* I can replicate the issue time and time again by doing the following procedure:

  - Start on a route that contains the stage
  - Route to a page that has no stage
  - Route back to the page that contains the stage

@lavrton Could you please try and reproduce, if you have any questions please let me know.

Thanks.

**Comment by deathblade89** [comment]
@lavrton 
I have created a demo here : https://codesandbox.io/s/536v6jr8yl

**Comment by deathblade89** [comment]
@lavrton Please get back to me as soon as you can, thank you!

**Comment by lavrton** [comment]
@deathblade89 I can't reproduce. It works ok for me. Tried on Chrome and Firefox.

**Comment by deathblade89** [comment]
Hi there,

Did you do the following?

Click go to stage
Go back
Click go to stage
try drag

**Comment by lavrton** [comment]
Ah. I see now. That was a bug in `vue-konva`. I fixed and published a new version. It should work ok now. Thanks for the report and a good demo.

The updated version of the demo with a small fix for moving the stage into a layer: https://codesandbox.io/s/pyqxm84nm7

**Comment by deathblade89** [comment]
@lavrton 
Thank you for the fix, works perfectly!
