### ISSUE TITLE
Example project in TypeScript

### ISSUE THREAD

**Issue by megasoft78** [konvajs/vue-konva#84]
Hi,
Is it possible to make it working using TypeScript?
It should be but I'm having trouble to setup it properly.
I have converted your basic example into TypeScript but the binding is not working and I'm really new to Vue. Would you mind to help me?
Here's my code:
![image](https://user-images.githubusercontent.com/514958/66994763-18b5af00-f0ce-11e9-938e-c1d79423d319.png)

**Comment by lavrton** [comment]
Personally I never tried `vue` with typescript. Can you make a sample repo? Probably with http://codesandbox.io/?

Do you have any errors?

**Comment by megasoft78** [comment]
Hi,
I created a simple example here:
(https://github.com/megasoft78/hello-world-vue-konva-typescript)

It's working now but I don't know how to change for instance the color of a circle.
I'm not sure how the binding is expected to work in this case. 
Could you please help me?

**Comment by megasoft78** [comment]
I found the solution and committed the change to that repository.
You could use it as reference for other people if you like.

Thank you! ;)

**Comment by megasoft78** [comment]
Unfortunatelly I have to reopen this issue as I don't know how to bind a v-image to a url.
The problem I'm having is that I don't know how to trigger the repaint event when I change the reference to a different image.
Any idea?

**Comment by megasoft78** [comment]
Unfortunatelly I have to reopen this issue as I don't know how to bind a v-image to a url.
The problem I'm having is that I don't know how to trigger the repaint event when I change the reference to a different image.
Any idea?

**Comment by megasoft78** [comment]
I force it to repaint by changing the x and y with a random number.
I committed my changes to this repository:
https://github.com/megasoft78/hello-world-vue-konva-typescript

What I want is to switch between images on click but change the position to force the repaint is not the solution.

Any idea to solve this issue?

**Comment by lavrton** [comment]
I created this demo from you code: https://codesandbox.io/s/vue-konva-template-7vn7p

It works ok for me.

**Comment by megasoft78** [comment]
I'm sorry but you did it in JavaScript. I need to use TypeScript.
Are you able to make my demo working without switching to JavaScript?

**Comment by lavrton** [comment]
Did you see that warning in the console? 
<img width="527" alt="Screenshot 2019-10-23 at 11 45 40" src="https://user-images.githubusercontent.com/1443320/67415449-adb31f00-f58a-11e9-96e2-f78475d0fce8.png">

**Comment by megasoft78** [comment]
Yes,
but I don't know why it's happening.
I'm new to Vue and KonvaJs. :(

**Comment by lavrton** [comment]
You need to define "image" property on the component. Right now you have just this:

```javascript
image!: HTMLImageElement;
```

With this code, you are telling typescript that the class will have a property with the type `HTMLImageElement`. But that property is not defined in the class. It doesn't have any value. 

If you have this in typescript:
```javascript
export default class App extends Vue {
  backgroundColor: string = "red";
  imageYoda!: HTMLImageElement;
  imageDarthVader!: HTMLImageElement;
  image!: HTMLImageElement;
  imageX: number = 200;
  imageY: number = 200;
  imageVisible: boolean = true;
}
```

It will be transpiled into this:
```javascript
export default class App extends Vue {
    constructor() {
        super(...arguments);
        this.backgroundColor = "red";
        this.imageX = 200;
        this.imageY = 200;
        this.imageVisible = true;
    }
}
```
https://www.typescriptlang.org/play/?ssl=9&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAgmGHKDMAHYLEBq6wcA3gFBxwBGqOA1gHMoEdHQDCETNABccAjCgBLGoLgBeOACIowBFoDcnOEoC2qQcACaEBKgCEcgBIAVALIAZAJLnLAUUxgU1oYIy4zC2AAEVRYAAsGVCQoRzhXTx9IgKCQsJNfYFT07wLs4JpQ4wjLAA05GnRTbmAoDTgAJgAGTrzq63rG5tbNLp6qgoYlAiVuQLluCClgVBo2xWYjAF8gA

You see, js version has no "image" property. So `vue` doesn't know about that property, so it can't make it reactive. So you don't see any updates.

The fix is simple. Just set any initial value into that property:

```typescript
image: HTMLImageElement | null = null;
```

**Comment by megasoft78** [comment]
Hi,
Thank you very much!
It's finally working now :)

I updated the repository for future reference:
https://github.com/megasoft78/hello-world-vue-konva-typescript
