### ISSUE TITLE
Mouse event issues

### ISSUE THREAD

**Issue by keehyuck** [konvajs/vue-konva#98]
Mouse events with modifiers are not working

For example,
@click.left, @click.shift.... are not possible.

Modifier keys with mouse event are possible for any tags in my Vue project,

but in v-konva tags(v-rect, v-image) they are not possible.

**Comment by lavrton** [comment]
I think it was working previously. Can you make a demo, please?

**Comment by keehyuck** [comment]
Hi @lavrton 

This is my demo
https://codesandbox.io/s/vue-konva-test-pfkzk?fontsize=14&hidenavigation=1&theme=dark

thanks.

**Comment by lavrton** [comment]
I see the issue. That is not trivial to enable all event modifiers from the `vue-konva` part.
It will take time to implement it.
As a workaround, I suggest just do all the logic with the event manually. Like if you need to check shift you can use
```javascript
handleClick(event) {
   const shitKey = event.evt.shitKey;
   if (shitKey) {
      // do something
   }
}
```

**Comment by lavrton** [comment]
*Note for anyone, who wants to implement it (probably me):*

`Vue` checks all requirements for the modifier from `event` object. But `Konva` pass custom event object (instead of native DOM event). To fix the issue we need to copy all required attributes from a native event into custom Konva event. 

Probably here: https://github.com/konvajs/vue-konva/blob/master/src/utils/index.js#L11

**Comment by doebi** [comment]
Altough @lavrton already summed it all and proposed a solution, I wanted to add another aspect to this.

<v-stage @click.prevent="handler"></v-stage>
Using the prevent modifier like this won't work, since returning a custom event object even breaks vue internals.

**Comment by lavrton** [comment]
Closing as not a priority. I don't think I can implement modifiers. But if anyone interested. Just make a pull request.
